[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = "2.7.4"
rustc-hash = "2.1.0"
seq-macro = "0.3.5"

[profile.dev]
opt-level = 1

[profile.release]
debug = true
lto = "thin"
codegen-units = 1
panic = "abort"
